### PR TITLE
Update to v0.14.1

### LINKED ISSUE #56: Update to be compatible on v0.14.1 PS release
Any interest on getting this updated to v0.14.1?

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #56 

PR isn't entirely complete, but it's at least a start. I couldn't build this locally due to issues with installing `sqlite3`.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Updating the `sqlite3` to latest version (`v5.0.2`) fixes the npm instal issue I was having.

Current compiler output. The 1 warning is due to `legacySuite` not having a type signature despite being a top-level member in the module. The warning prints a very long type signature, so I'm ignoring it for now.

```
[1/3 UnknownName] guide/src/SimpleE2E.purs:26:12

  26  dbconfig ∷ PostgreSQL.PoolConfiguration
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Unknown type PostgreSQL.PoolConfiguration

[2/3 UnknownName] guide/src/SimpleE2E.purs:212:10

  212    pool ← PostgreSQL.newPool dbconfig
                ^^^^^^^^^^^^^^^^^^
  
  Unknown value PostgreSQL.newPool

[3/3 UnknownImport] test/PG.purs:9:41

  9  import Database.PostgreSQL (Connection, PoolConfiguration, defaultPoolConfiguration)
                                             ^^^^^^^^^^^^^^^^^
  
  Cannot import type PoolConfiguration from module Database.PostgreSQL
  It either does not exist or the module does not export it.

           Src   Lib   All
Warnings   1     0     1  
Errors     3     0     3  
[error] Failed to build.
```

**Comment by JordanMartinez** [comment]
Alright. I think this PR actually compiles now. It's hard to test on my side locally because it uses docker and I'm not sure what commands to run to test it via that.

**Comment by Kamirus** [comment]
Cool! Nice work thanks! I'll look into it after Sunday when I'm back home

**Comment by JordanMartinez** [comment]
Thanks! Take your time.

**Comment by hjmtql** [comment]
> Alright. I think this PR actually compiles now. It's hard to test on my side locally because it uses docker and I'm not sure what commands to run to test it via that.

https://github.com/Kamirus/purescript-selda#info

Will it help you?
Run `docker-compose up -d` command to start up postgres, then `npm run test` to run the tests.

**Comment by Kamirus** [comment]
@JordanMartinez thank you so much for your work, I've merged this PR and my other PRs as well, branches are clean now with master being the most recent.
@hjmtql once again thanks for the CI update + docker setup and @paluh for `.env` changes, very handy!

**Comment by JordanMartinez** [comment]
@Kamirus Thanks! At the same time, my PR here expected the other PRs I had made to be merged into their respective libraries. If any one of those forks' branches are deleted, this library will no longer compile. 

What can we do to get those other PRs merged?

**Comment by Kamirus** [comment]
(Oh I did not get the notification about your comment, sorry for the delay @JordanMartinez )

[prettyprinter](https://github.com/JordanMartinez/purescript-prettyprinter) is no longer required and you can delete/archive it as we use [dodo-printer](https://github.com/natefaubion/purescript-dodo-printer) now.

Other dependencies are:
- postgresql-client
- polyform
- polyform-batteries-core
- polyform-batteries-env

and there we need to ask @paluh

**Pull request merged**
